// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ProcessFiles(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<void>;
